### ISSUE TITLE
Stay consistent with CSS code formatting.

### ISSUE THREAD

**Issue by josephtkim** [esinapaydin/prj-rev-bwfs-tea-cozy#6]
For the CSS code formatting, the best standards are to indent each property by 2 spaces. Here is how your code might look with this formatting applied

```css
body{
  background-color:black;
  font-family: "Helvetica", sans-serif;
  color: seashell;
  text-align: center;
  opacity: 0.9;
  font-size: 22px;
  margin: auto;
}

header{
  border-bottom: 1px solid seashell;
  align-items: center;
  height: 69px;
  position:fixed;
  background-color:black;
  width:100%;
  display:flex;
  flex-grow:1;
  flex-wrap: wrap;
  justify-content:center;
}
```
